### ISSUE TITLE
CLINT causes spurious interrupts after mtimecmp update

### ISSUE THREAD

**Issue by quic-egmc** [VP-Vibes/VPV-Peripherals#8]
When an OS is servicing a timer ISR it will typically write mtimecmp with a new value.

But the logic in clint::update_mtime depends on enough time having elapsed (as determined by the lfclk) before it will update the mtime_int_o output.  This means that if the ISR writes mtimecmp before the next lfclk tick occurs, a spurious timer interrupt will occur since mtime_int_o is still asserted.

In the cases where the mtime or mtimecmp registers are written, the timer state should be evaluated immediately so the mtime_int_o signal can deassert.

**Comment by eyck** [comment]
fixed with #9
